spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost/notifications_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    consumer:
      bootstrap-servers: cp-cp-kafka-headless:9092
      group_id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kosmar.notification.kafka.NotificationDeserializer
    producer:
      bootstrap-servers: cp-cp-kafka-headless:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kosmar.notification.kafka.NotificationSerializer
  main:
    allow-bean-definition-overriding: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

